name: 'Build and Unit Test'

on:
  push:
    branches-ignore:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build
        shell: bash
        run: npm install
      - name: Test
        shell: bash
        run: npm test
