name: Build & Publish Docker Image

on:
  workflow_dispatch:
    # branches: [ "main" ]
    inputs:
      version:
        type: string
        required: true


jobs:
  build-and-publish:
    runs-on: self-hosted
    steps:
    - name: Build and Publish Docker Image
      uses: gh-actions/docker-build-and-publish@d1e17fe1a9ab9efd6e60e8af3970e637f384ec05
      with:
        app-name: chandler-cup-backend
        version: ${{inputs.version}}