name: Build & Publish Docker Image

on:
  workflow_dispatch:
    # branches: [ "main" ]
    inputs:
      version:
        type: string
        required: true


jobs:
  build:
    runs-on: self-hosted
    steps:
    - name: Build and Publish Docker Image
      uses: gh-actions/docker-build-and-publish
      with:
        app-name: chandler-cup-backend
        version: ${{inputs.version}}