name: Build & Publish

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

  version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Version
        id: version
        uses: PaulHatch/semantic-version@v5.0.3
        with:
          version_format: "v${major}.${minor}.${patch}"
          major_pattern: "MAJOR"
          minor_pattern: "MINOR"
          bump_each_commit: true
      - name: Tag Version
        id: tag
        shell: bash
        run: |
          echo "Semantic version: ${{ steps.version.outputs.version }}"
          git tag ${{ steps.version.outputs.version }}
          git push origin --tags

  build-and-push:
    needs: [ setup, version ]
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: bossanova456
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          platforms: linux/arm64
          tags: |
            bossanova456/chandler-cup-backend:latest-arm64
